### PR TITLE
Update Contributors

### PR DESCRIPTION
**Pull request by nkatzman**
updating contributor email for Noah Katzman from yahoo-inc email to gmail

### CODE REVIEW

**Comment by FenrirUnbound** [comment]
Since you're already making an update to this repository, why not also update the [`package.json`](https://github.com/screwdriver-cd/generator-screwdriver/blob/master/package.json#L27)

**Comment by tkyi** [comment]
^^
https://github.com/screwdriver-cd/generator-screwdriver/blob/master/package.json#L27

**Comment by tkyi** [comment]
👍

**Comment by jer** [comment]
👎

**Comment by jer** [comment]
Actually 👍

**Comment by FenrirUnbound** [comment]
👍

**Pull request merged**
